services:
  scheduler:
    build: .
    image: ghcr.io/radiopy/radiopy:latest
    container_name: radiopy-scheduler
    environment:
      RADIOPY_CONFIG: |
        [redis]
        expiration = 1209600  # 2 weeks
        # cache_databsase is optional. If not present, the cache will be stored in the default database.
        cache_database = 1

        [redis.connection]
        host = "example.com"
        port = 6379
        username = "username"
        password = "password"
        decode_responses = true

        [spotify]
        client_id = "client_id"
        client_secret = "client_secret"
        redirect_uri = "http://127.0.0.1:8080/callback"
        scope = "playlist-modify-private playlist-modify-public"

        [ftp]  # optinal category
        hostname = "ftp.example.com"
        username = "username"
        password = "password"

    # volumes:
      # - ./config.toml:/app/config.toml  # alternative to using environment variables
      # - ./cronfile:/app/cronfile  # use this if you want to use a custom cronfile
